clc;
close all;
clear all;
clearvars;
M = 0.5;
m = 0.2;
b = 0.1;
I = 0.006;
g = 9.8;
l = 0.3;
p = I*(M+m)+M*m*l^2; %denominator for the A and B matrices

A = [0      1              0           0;
     0 -(I+m*l^2)*b/p  (m^2*g*l^2)/p   0;
     0      0              0           1;
     0 -(m*l*b)/p       m*g*l*(M+m)/p  0];
B = [0;
     (I+m*l^2)/p;
     0;
     m*l/p];
C = [1 0 0 0;
     0 0 1 0];
D = [0;
     0];
 figure;
sys_ss = ss(A, B, C, D);
poles = eig(A);
pc = poles;
Q = (C') * (C);
Q(1,1)=500;
Q(3,3)=10;
R = 1;
K = lqr(A, B, Q, R);
Ac = (A - B * K);
Bc = B;
Cc = C;
Dc = D;
sys_cl = ss(Ac, Bc, Cc, Dc);
t = 0:0.01:5;
r = 0.2 * ones(size(t));
[y, t, x] = lsim(sys_cl, r, t);
[AX, H1, H2] = plotyy(t, y(:, 1),t, y(:,2),'plot');
figure;
Cn=[1 0 0 0];
sys_ss=ss(A,B,Cn,0);
Nbar=rscale(sys_ss,K);
sys_cl = ss(Ac, Bc*Nbar, Cc, Dc);
t = 0:0.01:5;
r = 0.2 * ones(size(t));
[y, t, x] = lsim(sys_cl, r, t);
[AX, H1, H2] = plotyy(t, y(:, 1),t,y(:,2),'plot');